### ISSUE TITLE
Storage: Fix to make sure models files are stored properly

### ISSUE THREAD

**Issue by dvetal** [ayota/ddl_nlp#7]
Due to the fact that we are storing our corpus files in folds in a folder structure like the structure described in our README, we need to be able to store the k model files that are generated when gensim runs k times.  

Currently. The fun_3000.word2vec.py file is trying to save files to a folder that does not exist.

'models/jazz/2/train/jazz/2/train.model'

IDEAL: We'd like the folder structure to be built as a part of the end of the script.  
and to follow the pattern

models/<corpus>/<fold number>/train.model

Current Full traceback below:

Traceback (most recent call last):
  File "fun_3000/word2vec.py", line 79, in <module>
    run_model(opts.input_data_dir, opts.parallel_workers, opts.context_window, opts.hidden_layer, opts.model_name)  
  File "fun_3000/word2vec.py", line 66, in run_model
    model.save(model_path)
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1452, in save
    super(Word2Vec, self).save(_args, *_kwargs)
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/gensim/utils.py", line 486, in save
    pickle_protocol=pickle_protocol)
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/gensim/utils.py", line 359, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/gensim/utils.py", line 912, in pickle
    with smart_open(fname, 'wb') as fout:  # 'b' for binary, needed on Windows
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 99, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File "/Users/donaldvetal/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 379, in file_smart_open
    return open(fname, mode)
IOError: [Errno 2] No such file or directory: '/Users/donaldvetal/Projects/ddl_nlp/models/jazz/2/train/jazz/2/train.model'

**Comment by dvetal** [comment]
resolved.
